version: 1.19.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - mark/Revit2019
skip_tags: true
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore .\src\
build:
  project: .\src\RevitTestFramework.sln
  verbosity: minimal
test:
  assemblies:
    only:
    - .\bin\AnyCPU\Release\RunnerTests.dll
deploy:
- provider: NuGet
  api_key:
    secure: cN7zY+VTH8QH103SZn3xen5q3ZNqDvB4a5JKcYTGzBfnFRzCn/kldBPip6ENyCFF
  artifact: nupkg
  on:
    branch: mark/Revit2019